/*************************************** Copyright ******************************   
  * FileName   : Sin_w_gen_Config.H   
  * Version    : v1.0		
  * Author     : Lai-zs@qq.com	
  * Date       : 2022-12-22         
  * Description:    
  * Function List:  
  	1. ....
  	   <version>: 		
  <modify staff>:
  		  <data>:
   <description>:  
  	2. ...
  ******************************************************************************/


#ifndef __SIN_W_GEN__CONFIG_H_
#define __SIN_W_GEN__CONFIG_H_
/*include----------------------------------------------------------------------*/

#include "Sine_wave_generation.h"

/*define-----------------------------------------------------------------------*/


/*variate statement------------------------------------------------------------*/


/*function statement-----------------------------------------------------------*/

void SIN_Init(void);
uint16_t Get_CH1_Val(void);
uint16_t Get_CH2_Val(void);
uint16_t Get_CH3_Val(void);
uint16_t Get_CH4_Val(void);

#endif


 


